// <auto-generated />
using System;
using Acs.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Acs.Infrastructure.Data.Migrations
{
    [DbContext(typeof(AcsDbContext))]
    [Migration("20260828060005_PlanSourceCoordinates")]
    partial class PlanSourceCoordinates
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.19")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Acs.Domain.Entities.AccessRequest", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AutoAssignedDepartment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Justification")
                        .HasColumnType("longtext");

                    b.Property<int>("Kind")
                        .HasColumnType("int");

                    b.Property<int>("RequesterUserId")
                        .HasColumnType("int");

                    b.Property<int>("TargetEmployeeId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidUntil")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("RequesterUserId");

                    b.HasIndex("TargetEmployeeId");

                    b.ToTable("AccessRequests");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AccessRequestItem", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("AutoAdded")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("CurrentLevelOrder")
                        .HasColumnType("int");

                    b.Property<int>("CurrentStageOrder")
                        .HasColumnType("int");

                    b.Property<DateTime?>("DecidedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("LastReminderAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("MatrixId")
                        .HasColumnType("int");

                    b.Property<string>("PushResult")
                        .HasColumnType("longtext");

                    b.Property<DateTime?>("PushedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int?>("ReaderGroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ReaderId")
                        .HasColumnType("int");

                    b.Property<int>("RequestId")
                        .HasColumnType("int");

                    b.Property<int>("Status")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReaderGroupId");

                    b.HasIndex("ReaderId");

                    b.HasIndex("RequestId");

                    b.ToTable("AccessRequestItems");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AccessRequestItemStage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("MatrixId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId");

                    b.HasIndex("ItemId", "Order")
                        .IsUnique();

                    b.ToTable("AccessRequestItemStages");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AppUser", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("DisplayName")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<int?>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsLocal")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime(6)");

                    b.Property<bool>("MustChangePassword")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("longtext");

                    b.Property<int>("Roles")
                        .HasColumnType("int");

                    b.Property<string>("Theme")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("UserName")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ApprovalDecision", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Approved")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ApproverUserId")
                        .HasColumnType("int");

                    b.Property<string>("Comment")
                        .HasColumnType("longtext");

                    b.Property<DateTime>("DecidedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("ItemId")
                        .HasColumnType("int");

                    b.Property<int>("LevelOrder")
                        .HasColumnType("int");

                    b.Property<int?>("MatrixId")
                        .HasColumnType("int");

                    b.Property<int?>("OnBehalfOfUserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ApproverUserId");

                    b.HasIndex("ItemId");

                    b.ToTable("ApprovalDecisions");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ApprovalLevel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("MatrixId")
                        .HasColumnType("int");

                    b.Property<int>("Mode")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .HasColumnType("longtext");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<int?>("RequiredCount")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("MatrixId", "Order")
                        .IsUnique();

                    b.ToTable("ApprovalLevels");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ApprovalMatrix", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("ApprovalMatrices");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Approver", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdGroup")
                        .HasColumnType("longtext");

                    b.Property<int>("LevelId")
                        .HasColumnType("int");

                    b.Property<int?>("UserId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("LevelId");

                    b.HasIndex("UserId");

                    b.ToTable("Approvers");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AuditLog", b =>
                {
                    b.Property<long>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<long>("Id"));

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("At")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Details")
                        .HasColumnType("longtext");

                    b.Property<string>("Entity")
                        .HasColumnType("longtext");

                    b.Property<string>("EntityId")
                        .HasColumnType("longtext");

                    b.Property<string>("UserName")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("At");

                    b.ToTable("AuditLogs");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AutoAssignmentRule", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Department")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<int>("ReaderGroupId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ReaderGroupId");

                    b.ToTable("AutoAssignmentRules");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Building", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SchemaContentType")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("SchemaImage")
                        .HasColumnType("longblob");

                    b.HasKey("Id");

                    b.ToTable("Buildings");
                });

            modelBuilder.Entity("Acs.Domain.Entities.BuildingSection", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.ToTable("BuildingSections");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Corridor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int?>("ParentCorridorId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.HasIndex("ParentCorridorId");

                    b.ToTable("Corridors");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Deputy", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("DeputyUserId")
                        .HasColumnType("int");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("PrincipalUserId")
                        .HasColumnType("int");

                    b.Property<DateTime>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.HasKey("Id");

                    b.HasIndex("DeputyUserId");

                    b.HasIndex("PrincipalUserId");

                    b.ToTable("Deputies");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AdAccount")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("CardNumber")
                        .HasColumnType("longtext");

                    b.Property<string>("Department")
                        .HasColumnType("longtext");

                    b.Property<string>("Email")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalId")
                        .HasColumnType("varchar(255)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("PersonalNumber")
                        .HasColumnType("longtext");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<string>("WinPakCardHolderId")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.HasIndex("AdAccount");

                    b.HasIndex("ExternalId");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("Acs.Domain.Entities.EmployeeIdentifier", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("EmployeeId")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Note")
                        .HasColumnType("longtext");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<DateTime?>("ValidFrom")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime?>("ValidTo")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Value")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.HasKey("Id");

                    b.HasIndex("EmployeeId");

                    b.HasIndex("Type", "Value");

                    b.ToTable("EmployeeIdentifiers");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Floor", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("BuildingId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("SchemaContentType")
                        .HasColumnType("longtext");

                    b.Property<byte[]>("SchemaImage")
                        .HasColumnType("longblob");

                    b.Property<int?>("SectionId")
                        .HasColumnType("int");

                    b.Property<int>("SortOrder")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("BuildingId");

                    b.HasIndex("SectionId");

                    b.ToTable("Floors");
                });

            modelBuilder.Entity("Acs.Domain.Entities.PlanDevice", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<int>("Type")
                        .HasColumnType("int");

                    b.Property<double>("X")
                        .HasColumnType("double");

                    b.Property<double>("Y")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("FloorId");

                    b.ToTable("PlanDevices");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Reader", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AccessLevelExternalId")
                        .HasColumnType("longtext");

                    b.Property<string>("AccountName")
                        .HasColumnType("longtext");

                    b.Property<int?>("ApprovalMatrixId")
                        .HasColumnType("int");

                    b.Property<int?>("CorridorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<string>("ExternalId")
                        .HasColumnType("varchar(255)");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime?>("LastSyncedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.Property<string>("PanelName")
                        .HasColumnType("longtext");

                    b.Property<int?>("RoomId")
                        .HasColumnType("int");

                    b.Property<double?>("SchemaX")
                        .HasColumnType("double");

                    b.Property<double?>("SchemaY")
                        .HasColumnType("double");

                    b.Property<int>("Source")
                        .HasColumnType("int");

                    b.Property<double?>("SourceX")
                        .HasColumnType("double");

                    b.Property<double?>("SourceY")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalMatrixId");

                    b.HasIndex("CorridorId");

                    b.HasIndex("ExternalId");

                    b.HasIndex("RoomId");

                    b.ToTable("Readers");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ReaderDependency", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("ReaderId")
                        .HasColumnType("int");

                    b.Property<int>("RequiresReaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("RequiresReaderId");

                    b.HasIndex("ReaderId", "RequiresReaderId")
                        .IsUnique();

                    b.ToTable("ReaderDependencies");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ReaderGroup", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ApprovalMatrixId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<bool>("IsActive")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(256)
                        .HasColumnType("varchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("ApprovalMatrixId");

                    b.ToTable("ReaderGroups");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ReaderGroupMember", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("ChildGroupId")
                        .HasColumnType("int");

                    b.Property<int>("GroupId")
                        .HasColumnType("int");

                    b.Property<int?>("ReaderId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ChildGroupId");

                    b.HasIndex("GroupId");

                    b.HasIndex("ReaderId");

                    b.ToTable("ReaderGroupMembers");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Room", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CorridorId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("longtext");

                    b.Property<int>("FloorId")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<double?>("PlanH")
                        .HasColumnType("double");

                    b.Property<double?>("PlanW")
                        .HasColumnType("double");

                    b.Property<double?>("PlanX")
                        .HasColumnType("double");

                    b.Property<double?>("PlanY")
                        .HasColumnType("double");

                    b.Property<double?>("SourceX")
                        .HasColumnType("double");

                    b.Property<double?>("SourceY")
                        .HasColumnType("double");

                    b.HasKey("Id");

                    b.HasIndex("CorridorId");

                    b.HasIndex("FloorId");

                    b.ToTable("Rooms");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Setting", b =>
                {
                    b.Property<string>("Key")
                        .HasMaxLength(128)
                        .HasColumnType("varchar(128)");

                    b.Property<bool>("IsSecret")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<string>("UpdatedBy")
                        .HasColumnType("longtext");

                    b.Property<string>("Value")
                        .HasColumnType("longtext");

                    b.HasKey("Key");

                    b.ToTable("Settings");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.DataProtection.EntityFrameworkCore.DataProtectionKey", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    MySqlPropertyBuilderExtensions.UseMySqlIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("FriendlyName")
                        .HasColumnType("longtext");

                    b.Property<string>("Xml")
                        .HasColumnType("longtext");

                    b.HasKey("Id");

                    b.ToTable("DataProtectionKeys");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AccessRequest", b =>
                {
                    b.HasOne("Acs.Domain.Entities.AppUser", "RequesterUser")
                        .WithMany()
                        .HasForeignKey("RequesterUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Acs.Domain.Entities.Employee", "TargetEmployee")
                        .WithMany()
                        .HasForeignKey("TargetEmployeeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("RequesterUser");

                    b.Navigation("TargetEmployee");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AccessRequestItem", b =>
                {
                    b.HasOne("Acs.Domain.Entities.ReaderGroup", "ReaderGroup")
                        .WithMany()
                        .HasForeignKey("ReaderGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Acs.Domain.Entities.Reader", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Acs.Domain.Entities.AccessRequest", "Request")
                        .WithMany("Items")
                        .HasForeignKey("RequestId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reader");

                    b.Navigation("ReaderGroup");

                    b.Navigation("Request");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AccessRequestItemStage", b =>
                {
                    b.HasOne("Acs.Domain.Entities.AccessRequestItem", "Item")
                        .WithMany("Stages")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acs.Domain.Entities.ApprovalMatrix", "Matrix")
                        .WithMany()
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Item");

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AppUser", b =>
                {
                    b.HasOne("Acs.Domain.Entities.Employee", "Employee")
                        .WithMany()
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ApprovalDecision", b =>
                {
                    b.HasOne("Acs.Domain.Entities.AppUser", "ApproverUser")
                        .WithMany()
                        .HasForeignKey("ApproverUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Acs.Domain.Entities.AccessRequestItem", "Item")
                        .WithMany("Decisions")
                        .HasForeignKey("ItemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ApproverUser");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ApprovalLevel", b =>
                {
                    b.HasOne("Acs.Domain.Entities.ApprovalMatrix", "Matrix")
                        .WithMany("Levels")
                        .HasForeignKey("MatrixId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Matrix");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Approver", b =>
                {
                    b.HasOne("Acs.Domain.Entities.ApprovalLevel", "Level")
                        .WithMany("Approvers")
                        .HasForeignKey("LevelId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acs.Domain.Entities.AppUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Level");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AutoAssignmentRule", b =>
                {
                    b.HasOne("Acs.Domain.Entities.ReaderGroup", "ReaderGroup")
                        .WithMany()
                        .HasForeignKey("ReaderGroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("ReaderGroup");
                });

            modelBuilder.Entity("Acs.Domain.Entities.BuildingSection", b =>
                {
                    b.HasOne("Acs.Domain.Entities.Building", "Building")
                        .WithMany("Sections")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Building");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Corridor", b =>
                {
                    b.HasOne("Acs.Domain.Entities.Floor", "Floor")
                        .WithMany("Corridors")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acs.Domain.Entities.Corridor", "ParentCorridor")
                        .WithMany()
                        .HasForeignKey("ParentCorridorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Floor");

                    b.Navigation("ParentCorridor");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Deputy", b =>
                {
                    b.HasOne("Acs.Domain.Entities.AppUser", "DeputyUser")
                        .WithMany()
                        .HasForeignKey("DeputyUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acs.Domain.Entities.AppUser", "PrincipalUser")
                        .WithMany()
                        .HasForeignKey("PrincipalUserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("DeputyUser");

                    b.Navigation("PrincipalUser");
                });

            modelBuilder.Entity("Acs.Domain.Entities.EmployeeIdentifier", b =>
                {
                    b.HasOne("Acs.Domain.Entities.Employee", "Employee")
                        .WithMany("Identifiers")
                        .HasForeignKey("EmployeeId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Employee");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Floor", b =>
                {
                    b.HasOne("Acs.Domain.Entities.Building", "Building")
                        .WithMany("Floors")
                        .HasForeignKey("BuildingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acs.Domain.Entities.BuildingSection", "Section")
                        .WithMany("Floors")
                        .HasForeignKey("SectionId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Building");

                    b.Navigation("Section");
                });

            modelBuilder.Entity("Acs.Domain.Entities.PlanDevice", b =>
                {
                    b.HasOne("Acs.Domain.Entities.Floor", "Floor")
                        .WithMany()
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Reader", b =>
                {
                    b.HasOne("Acs.Domain.Entities.ApprovalMatrix", "ApprovalMatrix")
                        .WithMany()
                        .HasForeignKey("ApprovalMatrixId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Acs.Domain.Entities.Corridor", "Corridor")
                        .WithMany("Readers")
                        .HasForeignKey("CorridorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Acs.Domain.Entities.Room", "Room")
                        .WithMany("Readers")
                        .HasForeignKey("RoomId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovalMatrix");

                    b.Navigation("Corridor");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ReaderDependency", b =>
                {
                    b.HasOne("Acs.Domain.Entities.Reader", "Reader")
                        .WithMany("Dependencies")
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acs.Domain.Entities.Reader", "RequiresReader")
                        .WithMany()
                        .HasForeignKey("RequiresReaderId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Reader");

                    b.Navigation("RequiresReader");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ReaderGroup", b =>
                {
                    b.HasOne("Acs.Domain.Entities.ApprovalMatrix", "ApprovalMatrix")
                        .WithMany()
                        .HasForeignKey("ApprovalMatrixId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("ApprovalMatrix");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ReaderGroupMember", b =>
                {
                    b.HasOne("Acs.Domain.Entities.ReaderGroup", "ChildGroup")
                        .WithMany()
                        .HasForeignKey("ChildGroupId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Acs.Domain.Entities.ReaderGroup", "Group")
                        .WithMany("Members")
                        .HasForeignKey("GroupId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Acs.Domain.Entities.Reader", "Reader")
                        .WithMany()
                        .HasForeignKey("ReaderId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("ChildGroup");

                    b.Navigation("Group");

                    b.Navigation("Reader");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Room", b =>
                {
                    b.HasOne("Acs.Domain.Entities.Corridor", "Corridor")
                        .WithMany("Rooms")
                        .HasForeignKey("CorridorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Acs.Domain.Entities.Floor", "Floor")
                        .WithMany("Rooms")
                        .HasForeignKey("FloorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Corridor");

                    b.Navigation("Floor");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AccessRequest", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("Acs.Domain.Entities.AccessRequestItem", b =>
                {
                    b.Navigation("Decisions");

                    b.Navigation("Stages");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ApprovalLevel", b =>
                {
                    b.Navigation("Approvers");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ApprovalMatrix", b =>
                {
                    b.Navigation("Levels");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Building", b =>
                {
                    b.Navigation("Floors");

                    b.Navigation("Sections");
                });

            modelBuilder.Entity("Acs.Domain.Entities.BuildingSection", b =>
                {
                    b.Navigation("Floors");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Corridor", b =>
                {
                    b.Navigation("Readers");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Employee", b =>
                {
                    b.Navigation("Identifiers");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Floor", b =>
                {
                    b.Navigation("Corridors");

                    b.Navigation("Rooms");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Reader", b =>
                {
                    b.Navigation("Dependencies");
                });

            modelBuilder.Entity("Acs.Domain.Entities.ReaderGroup", b =>
                {
                    b.Navigation("Members");
                });

            modelBuilder.Entity("Acs.Domain.Entities.Room", b =>
                {
                    b.Navigation("Readers");
                });
#pragma warning restore 612, 618
        }
    }
}
